### ISSUE TITLE
Rename `useTriggersBreakpoint` -> `useBP`

### ISSUE THREAD

**Issue by realStandal** [LockTech/atomic#18]
`useTriggersBreakpoint` is verbose, and for a hook which is designed for quick, easy, and ambiguous re-use - this contradicts that model.

**Comment by harshi1122** [comment]
Hello
Do I need to replace every occurrence of useTriggersBreakpoint with useBP?

**Comment by realStandal** [comment]
Nice to meet you @harshi1122!

Yes, and then if I broke it down into a complete list of items:

- [ ] - Update, replace, and rename (the file) at [`src/hooks/useBreakpoint`](https://github.com/LockTech/atomic/blob/f77172a0c9f177025a0ff0c1421a4af05d4ee56c/src/hooks/useBreakpoint.ts#L29)
- [ ] - Update, replace, and rename (the file) at [`stories/hooks/useTriggersBreakpoint`](https://github.com/LockTech/atomic/blob/main/stories/hooks/useTriggersBreakpoint.stories.mdx)
- [ ] - Update `useTriggersBreakpoint` -> `useBP` throughout the source (should be safe searching all files in `/src/` and `/stories/`)

Are you thinking of taking this on? If so let me know so I can assign you :) and if you think of a better name, feel free to use it: `useBP` just felt easy to remember/type.

**Comment by harshi1122** [comment]
@realStandal 
Please assign it to me. I would love to work on it!

**Comment by harshi1122** [comment]
and i don't have suggestions about the name so let's go with useBP :)

**Comment by harshi1122** [comment]
@realStandal 
May I know what's the difference between useBreakPoint and useTriggersBreakpoint?
I believe I shouldn't be changing useBreakPoint
Also to not confuse the two, is it okay to use useTBP instead?

**Comment by realStandal** [comment]
@harshi1122

> May I know what's the difference between useBreakPoint and useTriggersBreakpoint?

* [`useBreakpoint`](https://github.com/LockTech/atomic/blob/f77172a0c9f177025a0ff0c1421a4af05d4ee56c/src/theme/breakpoint.tsx#L38) provides a key-value map of the configured breakpoints to their width (`{ 'sm': '200px', 'xl': '2000px', ...}`).
* [`useTriggersBreakpoint`](https://github.com/LockTech/atomic/blob/main/src/hooks/useBreakpoint.ts#L29) returns a `boolean` depending on if the provided breakpoint (or an abitrary width) triggers the [width media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/width).
  * The `useTriggersBreakpoint` hook is in a file named `useBreakpoint`, but you can rename this file to match the hook's name.

> I believe I shouldn't be changing useBreakPoint

You are correct.

> Also to not confuse the two, is it okay to use useTBP instead?

Hmm, I'm not the biggest fan of `useTBP`. What about `useMediaWidth` or something which builds off the fact this hook uses the width media-feature, and just supports specific breakpoints?

**Comment by harshi1122** [comment]
hi @realStandal 
i shall go with useMediaWidth

**Comment by harshi1122** [comment]
Could you check my PR and suggest changes if necessary.
Thanks

**Comment by realStandal** [comment]
> Could you check my PR and suggest changes if necessary.
> Thanks

Awesome! Thanks :)
