### ISSUE TITLE
Add `'input-error'` and `'input-success` classes

### ISSUE THREAD

**Issue by realStandal** [LockTech/atomic#6]
Super simple classes which will `color` their content to ~match~ resemble the coloring used by input validation states. Readability should take a higher precedence than matching.

**Comment by realStandal** [comment]
Example:

![image](https://user-images.githubusercontent.com/25166787/132257670-cfe52a25-19e1-4918-ae40-247da52c6ec5.png)

**Comment by swarup4741** [comment]
Can I work on this issue ?

**Comment by realStandal** [comment]
@swarup4741 for sure! I was thinking of plopping it down next to whatever layer `input-label` is currently in (input can be found under `src/components/input.js`). Lmk if you need any pointers!

**Comment by realStandal** [comment]
And you'll probably need to add the`label` suffix so it doesn't conflict with the inputs existing validation classes

**Comment by swarup4741** [comment]
so i need to make classes like `input-label-error` and `input-label-success` which will color the input validation label. Am i right?

**Comment by swarup4741** [comment]
So what shall I do now exactly ? if you please guide me..

**Comment by realStandal** [comment]
Yeah, that's great! If I had to nit-pick it I'd rename `-content` to `-label`, but that's 100% your choice.

Now there is a `stories/components/Input.stories.mdx`. This is where the Input's storybook documentation is located. Personally, I'd add something along the following to the `## Validation` section:

```mdx
## Validation

`'input-error'` and `'input-success'` classes can be added to the element making use of 'input' to mark the input's value, or lackof, errorful or successful.

`'input-error-content'` and `'input-success-content'` can be used to quickly styling additional, contextual information in response to an input having an error or being successfully filled out.

<Canvas>
  <Story name="Error">
    <label className="input-group">
      <p className="input-label">Error</p>
      <input className="input input-error" placeholder="An errorful empty input" />
      <p className="input-error-content>Oh no! An error!</p>
    </label>
  </Story>
</Canvas>

// success example
```

However you want to document it is up to you, whatever makes the most sense/is the most helpful in your opinion.

Once you're happy with it all, [you'll need to make a PR](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) from your repository's branch into this repository's and we can double-check your code from there :)

P.s. sorry about the time zone differences lol

**Comment by swarup4741** [comment]
ok.. I'm making it `input-success-label` and `input-error-label` and also adding them as a documentation in `Input.stories.mdx`. I hope that we will be fine. Also thanks a lot for such an amazing guidance 😄

**Comment by realStandal** [comment]
No problem and sounds good!

**Comment by swarup4741** [comment]
> No problem and sounds good!

I have created a PR

**Comment by realStandal** [comment]
Thanks again @swarup4741!
